# Site settings
title: Joe Letchford...
description:
baseurl: "/joeletchford"
url: ""

contact:
  email:
  twitter:
  github:
  facebook:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md, .sass-cache, .git]
sass:
  style: compressed
